### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by maschwenk** [bugcrowd/vrt-ruby#28]
It'd be great to have a pull request template with a note about adding an entry to the changelog, not changing version.rb, etc.

**Comment by adamrdavid** [comment]
resolved

**Comment by raselmr831-jpg** [comment]
> resolved

![Screenshot_2026-06-30-19-10-47-378_com.bKash.merchantapp.jpg](https://github.com/user-attachments/assets/764f9515-5457-4576-9b64-3472c0a3cfe7)

Banking mobile payment

**Comment by raselmr831-jpg** [comment]
Ad
